### ISSUE TITLE
Support for CATEGORICAL & Extra warning messages

### ISSUE THREAD

**Issue by aelhelou** [mathworks-ref-arch/matlab-parquet#2]
parquetWrite is throwing error when dataset has CATEGORICAL variables.

Current work-around is to cast as string before.

Also warning messages are thrown in general when running on Windows:
![image](https://user-images.githubusercontent.com/32584755/59630302-d9fcf180-90f9-11e9-9d82-6b6560ddba14.png)

**Comment by asollander** [comment]
Hi, thanks a lot for providing this feedback. We are aware of this situation and will take your feedback as a feature request.

**Comment by asollander** [comment]
Closing this issue, as this package has been sunset.
